In [1]:
import pandas as pd

In [2]:
usage_df = pd.read_csv("../data/raw/ev_charging_session_dataset.csv")

In [3]:
usage_df.shape
usage_df.info() 
usage_df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Station_ID           500 non-null    str
 1   City                 500 non-null    str
 2   Date                 500 non-null    str
 3   Vehicle_Type         500 non-null    str
 4   Charging_Start_Time  500 non-null    str
 5   Charging_End_Time    500 non-null    str
 6   Energy_Consumed_kWh  500 non-null    float64
 7   Cost_INR             500 non-null    float64
 8   Payment_Method       500 non-null    str
dtypes: float64(2), str(7)
memory usage: 35.3 KB

,Station_ID,City,Date,Vehicle_Type,Charging_Start_Time,Charging_End_Time,Energy_Consumed_kWh,Cost_INR,Payment_Method
count,500,500,500,500,500,500,500.000000,500.00000,500
unique,500,10,1,4,384,386,NaN,NaN,3
top,ST001,Delhi,2025-10-15,Truck,08:14,18:54,NaN,NaN,Cash
freq,1,58,500,132,4,3,NaN,NaN,169
mean,NaN,NaN,NaN,NaN,NaN,NaN,52.680400,526.80400,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,27.589008,275.89008,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,3.200000,32.00000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,28.650000,286.50000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,51.600000,516.00000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,76.225000,762.25000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,99.900000,999.00000,NaN

In [4]:

usage_df.head()

,Station_ID,City,Date,Vehicle_Type,Charging_Start_Time,Charging_End_Time,Energy_Consumed_kWh,Cost_INR,Payment_Method
0,ST001,Kolkata,2025-10-15,Car,12:14,13:57,96.2,962.0,UPI
1,ST002,Pune,2025-10-15,Bus,15:27,17:26,59.2,592.0,UPI
2,ST003,Hyderabad,2025-10-15,Car,11:29,12:08,59.8,598.0,Cash
3,ST004,Indore,2025-10-15,Bus,10:12,11:45,38.3,383.0,Cash
4,ST005,Indore,2025-10-15,Car,10:19,11:03,48.9,489.0,Card

In [5]:
usage_df["Date"] = pd.to_datetime(usage_df["Date"])

In [6]:
usage_df["Charging_Start"] = pd.to_datetime(
    usage_df["Date"].dt.strftime("%Y-%m-%d") + " " +
    usage_df["Charging_Start_Time"]
)

usage_df["Charging_End"] = pd.to_datetime(
    usage_df["Date"].dt.strftime("%Y-%m-%d") + " " +
    usage_df["Charging_End_Time"]
)

In [7]:
usage_df.head()

,Station_ID,City,Date,Vehicle_Type,Charging_Start_Time,Charging_End_Time,Energy_Consumed_kWh,Cost_INR,Payment_Method,Charging_Start,Charging_End
0,ST001,Kolkata,2025-10-15,Car,12:14,13:57,96.2,962.0,UPI,2025-10-15 12:14:00,2025-10-15 13:57:00
1,ST002,Pune,2025-10-15,Bus,15:27,17:26,59.2,592.0,UPI,2025-10-15 15:27:00,2025-10-15 17:26:00
2,ST003,Hyderabad,2025-10-15,Car,11:29,12:08,59.8,598.0,Cash,2025-10-15 11:29:00,2025-10-15 12:08:00
3,ST004,Indore,2025-10-15,Bus,10:12,11:45,38.3,383.0,Cash,2025-10-15 10:12:00,2025-10-15 11:45:00
4,ST005,Indore,2025-10-15,Car,10:19,11:03,48.9,489.0,Card,2025-10-15 10:19:00,2025-10-15 11:03:00

In [8]:
usage_df["Session_Duration_Minutes"] = (
    usage_df["Charging_End"] - usage_df["Charging_Start"]
).dt.total_seconds() / 60

In [9]:
usage_df[["Charging_Start", "Charging_End", "Session_Duration_Minutes"]].head()

       Charging_Start        Charging_End  Session_Duration_Minutes
0 2025-10-15 12:14:00 2025-10-15 13:57:00                     103.0
1 2025-10-15 15:27:00 2025-10-15 17:26:00                     119.0
2 2025-10-15 11:29:00 2025-10-15 12:08:00                      39.0
3 2025-10-15 10:12:00 2025-10-15 11:45:00                      93.0
4 2025-10-15 10:19:00 2025-10-15 11:03:00                      44.0

In [10]:
usage_df["Start_Hour"] = usage_df["Charging_Start"].dt.hour

In [11]:
usage_df["End_Hour"] = usage_df["Charging_End"].dt.hour

In [12]:
usage_df["Day_of_Week"] = usage_df["Date"].dt.day_name()

In [13]:
usage_df["Is_Weekend"] = usage_df["Date"].dt.weekday >= 5

In [14]:
usage_df["Month"] = usage_df["Date"].dt.month

In [15]:
usage_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Station_ID                500 non-null    str
 1   City                      500 non-null    str
 2   Date                      500 non-null    datetime64[us]
 3   Vehicle_Type              500 non-null    str
 4   Charging_Start_Time       500 non-null    str
 5   Charging_End_Time         500 non-null    str
 6   Energy_Consumed_kWh       500 non-null    float64
 7   Cost_INR                  500 non-null    float64
 8   Payment_Method            500 non-null    str
 9   Charging_Start            500 non-null    datetime64[us]
 10  Charging_End              500 non-null    datetime64[us]
 11  Session_Duration_Minutes  500 non-null    float64
 12  Start_Hour                500 non-null    int32
 13  End_Hour                  500 non-null    int32
 14  Day_of_Week               500 non-null    str
 15  Is_Weekend                500 non-null    bool
 16  Month                     500 non-null    int32
dtypes: bool(1), datetime64[us](3), float64(3), int32(3), str(7)
memory usage: 57.3 KB

In [17]:
usage_df[usage_df["City"] == "Delhi"]

,Station_ID,City,Date,Vehicle_Type,Charging_Start_Time,Charging_End_Time,Energy_Consumed_kWh,Cost_INR,Payment_Method,Charging_Start,Charging_End,Session_Duration_Minutes,Start_Hour,End_Hour,Day_of_Week,Is_Weekend,Month
6,ST007,Delhi,2025-10-15,Truck,06:04,08:44,77.9,779.0,Card,2025-10-15 06:04:00,2025-10-15 08:44:00,160.0,6,8,Wednesday,False,10
29,ST030,Delhi,2025-10-15,Bike,16:05,16:56,64.9,649.0,UPI,2025-10-15 16:05:00,2025-10-15 16:56:00,51.0,16,16,Wednesday,False,10
30,ST031,Delhi,2025-10-15,Truck,07:50,10:24,87.3,873.0,Cash,2025-10-15 07:50:00,2025-10-15 10:24:00,154.0,7,10,Wednesday,False,10
45,ST046,Delhi,2025-10-15,Bus,14:43,15:38,23.0,230.0,Card,2025-10-15 14:43:00,2025-10-15 15:38:00,55.0,14,15,Wednesday,False,10
72,ST073,Delhi,2025-10-15,Car,16:54,18:22,42.5,425.0,Card,2025-10-15 16:54:00,2025-10-15 18:22:00,88.0,16,18,Wednesday,False,10
82,ST083,Delhi,2025-10-15,Car,20:26,21:06,88.0,880.0,Card,2025-10-15 20:26:00,2025-10-15 21:06:00,40.0,20,21,Wednesday,False,10
83,ST084,Delhi,2025-10-15,Bike,08:58,10:31,74.4,744.0,Cash,2025-10-15 08:58:00,2025-10-15 10:31:00,93.0,8,10,Wednesday,False,10
84,ST085,Delhi,2025-10-15,Bus,08:55,11:25,68.5,685.0,UPI,2025-10-15 08:55:00,2025-10-15 11:25:00,150.0,8,11,Wednesday,False,10
108,ST109,Delhi,2025-10-15,Truck,18:45,21:01,74.3,743.0,Cash,2025-10-15 18:45:00,2025-10-15 21:01:00,136.0,18,21,Wednesday,False,10
118,ST119,Delhi,2025-10-15,Bike,11:04,13:36,97.4,974.0,Card,2025-10-15 11:04:00,2025-10-15 13:36:00,152.0,11,13,Wednesday,False,10
120,ST121,Delhi,2025-10-15,Truck,06:45,07:15,50.9,509.0,UPI,2025-10-15 06:45:00,2025-10-15 07:15:00,30.0,6,7,Wednesday,False,10
124,ST125,Delhi,2025-10-15,Truck,18:06,20:15,82.5,825.0,Card,2025-10-15 18:06:00,2025-10-15 20:15:00,129.0,18,20,Wednesday,False,10
127,ST128,Delhi,2025-10-15,Truck,11:47,14:24,49.5,495.0,Cash,2025-10-15 11:47:00,2025-10-15 14:24:00,157.0,11,14,Wednesday,False,10
129,ST130,Delhi,2025-10-15,Truck,12:35,14:26,43.3,433.0,Cash,2025-10-15 12:35:00,2025-10-15 14:26:00,111.0,12,14,Wednesday,False,10
138,ST139,Delhi,2025-10-15,Bus,12:06,13:44,87.8,878.0,Card,2025-10-15 12:06:00,2025-10-15 13:44:00,98.0,12,13,Wednesday,False,10
156,ST157,Delhi,2025-10-15,Car,18:55,20:34,31.4,314.0,Cash,2025-10-15 18:55:00,2025-10-15 20:34:00,99.0,18,20,Wednesday,False,10
160,ST161,Delhi,2025-10-15,Bike,11:35,13:33,45.3,453.0,Cash,2025-10-15 11:35:00,2025-10-15 13:33:00,118.0,11,13,Wednesday,False,10
169,ST170,Delhi,2025-10-15,Bus,06:28,07:48,11.1,111.0,UPI,2025-10-15 06:28:00,2025-10-15 07:48:00,80.0,6,7,Wednesday,False,10
173,ST174,Delhi,2025-10-15,Car,10:04,12:29,75.3,753.0,UPI,2025-10-15 10:04:00,2025-10-15 12:29:00,145.0,10,12,Wednesday,False,10
174,ST175,Delhi,2025-10-15,Bus,19:57,22:21,97.4,974.0,Cash,2025-10-15 19:57:00,2025-10-15 22:21:00,144.0,19,22,Wednesday,False,10
179,ST180,Delhi,2025-10-15,Bike,14:50,15:32,22.3,223.0,Card,2025-10-15 14:50:00,2025-10-15 15:32:00,42.0,14,15,Wednesday,False,10
184,ST185,Delhi,2025-10-15,Truck,14:13,17:09,79.5,795.0,Card,2025-10-15 14:13:00,2025-10-15 17:09:00,176.0,14,17,Wednesday,False,10
191,ST192,Delhi,2025-10-15,Bike,20:12,22:12,23.9,239.0,UPI,2025-10-15 20:12:00,2025-10-15 22:12:00,120.0,20,22,Wednesday,False,10
197,ST198,Delhi,2025-10-15,Bike,17:40,18:40,11.0,110.0,UPI,2025-10-15 17:40:00,2025-10-15 18:40:00,60.0,17,18,Wednesday,False,10
232,ST233,Delhi,2025-10-15,Truck,19:19,22:00,82.6,826.0,UPI,2025-10-15 19:19:00,2025-10-15 22:00:00,161.0,19,22,Wednesday,False,10
235,ST236,Delhi,2025-10-15,Bike,15:38,16:54,95.3,953.0,Cash,2025-10-15 15:38:00,2025-10-15 16:54:00,76.0,15,16,Wednesday,False,10
243,ST244,Delhi,2025-10-15,Truck,16:40,19:18,20.1,201.0,Cash,2025-10-15 16:40:00,2025-10-15 19:18:00,158.0,16,19,Wednesday,False,10
255,ST256,Delhi,2025-10-15,Car,10:28,12:11,81.5,815.0,UPI,2025-10-15 10:28:00,2025-10-15 12:11:00,103.0,10,12,Wednesday,False,10
262,ST263,Delhi,2025-10-15,Bike,15:26,17:23,37.7,377.0,Card,2025-10-15 15:26:00,2025-10-15 17:23:00,117.0,15,17,Wednesday,False,10
270,ST271,Delhi,2025-10-15,Bus,07:53,09:33,77.2,772.0,UPI,2025-10-15 07:53:00,2025-10-15 09:33:00,100.0,7,9,Wednesday,False,10
298,ST299,Delhi,2025-10-15,Bus,11:39,12:39,72.9,729.0,UPI,2025-10-15 11:39:00,2025-10-15 12:39:00,60.0,11,12,Wednesday,False,10
302,ST303,Delhi,2025-10-15,Car,15:28,17:19,50.1,501.0,Card,2025-10-15 15:28:00,2025-10-15 17:19:00,111.0,15,17,Wednesday,False,10
306,ST307,Delhi,2025-10-15,Bike,06:49,09:11,30.0,300.0,Card,2025-10-15 06:49:00,2025-10-15 09:11:00,142.0,6,9,Wednesday,False,10
312,ST313,Delhi,2025-10-15,Bus,07:11,08:56,99.2,992.0,UPI,2025-10-15 07:11:00,2025-10-15 08:56:00,105.0,7,8,Wednesday,False,10
315,ST316,Delhi,2025-10-15,Car,08:42,10:27,88.0,880.0,Card,2025-10-15 08:42:00,2025-10-15 10:27:00,105.0,8,10,Wednesday,False,10
317,ST318,Delhi,2025-10-15,Truck,16:19,17:45,99.5,995.0,UPI,2025-10-15 16:19:00,2025-10-15 17:45:00,86.0,16,17,Wednesday,False,10
341,ST342,Delhi,2025-10-15,Bike,18:32,19:27,47.0,470.0,UPI,2025-10-15 18:32:00,2025-10-15 19:27:00,55.0,18,19,Wednesday,False,10
359,ST360,Delhi,2025-10-15,Truck,16:36,19:09,69.8,698.0,Card,2025-10-15 16:36:00,2025-10-15 19:09:00,153.0,16,19,Wednesday,False,10
368,ST369,Delhi,2025-10-15,Car,19:20,21:08,81.8,818.0,Cash,2025-10-15 19:20:00,2025-10-15 21:08:00,108.0,19,21,Wednesday,False,10
379,ST380,Delhi,2025-10-15,Truck,19:01,21:26,89.4,894.0,Card,2025-10-15 19:01:00,2025-10-15 21:26:00,145.0,19,21,Wednesday,False,10
396,ST397,Delhi,2025-10-15,Truck,12:30,13:18,21.9,219.0,Card,2025-10-15 12:30:00,2025-10-15 13:18:00,48.0,12,13,Wednesday,False,10
398,ST399,Delhi,2025-10-15,Bike,16:39,18:21,52.4,524.0,Cash,2025-10-15 16:39:00,2025-10-15 18:21:00,102.0,16,18,Wednesday,False,10
403,ST404,Delhi,2025-10-15,Car,17:47,20:23,69.3,693.0,UPI,2025-10-15 17:47:00,2025-10-15 20:23:00,156.0,17,20,Wednesday,False,10
419,ST420,Delhi,2025-10-15,Car,08:26,08:59,32.5,325.0,UPI,2025-10-15 08:26:00,2025-10-15 08:59:00,33.0,8,8,Wednesday,False,10
420,ST421,Delhi,2025-10-15,Car,17:51,20:50,73.2,732.0,Cash,2025-10-15 17:51:00,2025-10-15 20:50:00,179.0,17,20,Wednesday,False,10
427,ST428,Delhi,2025-10-15,Truck,06:20,07:30,99.3,993.0,Card,2025-10-15 06:20:00,2025-10-15 07:30:00,70.0,6,7,Wednesday,False,10
439,ST440,Delhi,2025-10-15,Bike,18:24,20:09,41.8,418.0,UPI,2025-10-15 18:24:00,2025-10-15 20:09:00,105.0,18,20,Wednesday,False,10
444,ST445,Delhi,2025-10-15,Bus,19:14,20:16,97.5,975.0,Cash,2025-10-15 19:14:00,2025-10-15 20:16:00,62.0,19,20,Wednesday,False,10
448,ST449,Delhi,2025-10-15,Bus,07:25,09:55,10.6,106.0,Cash,2025-10-15 07:25:00,2025-10-15 09:55:00,150.0,7,9,Wednesday,False,10
450,ST451,Delhi,2025-10-15,Bus,17:20,19:35,86.9,869.0,Card,2025-10-15 17:20:00,2025-10-15 19:35:00,135.0,17,19,Wednesday,False,10
451,ST452,Delhi,2025-10-15,Bike,13:36,16:00,18.4,184.0,UPI,2025-10-15 13:36:00,2025-10-15 16:00:00,144.0,13,16,Wednesday,False,10
459,ST460,Delhi,2025-10-15,Bike,10:42,11:38,60.0,600.0,UPI,2025-10-15 10:42:00,2025-10-15 11:38:00,56.0,10,11,Wednesday,False,10
461,ST462,Delhi,2025-10-15,Car,13:30,15:13,65.9,659.0,Card,2025-10-15 13:30:00,2025-10-15 15:13:00,103.0,13,15,Wednesday,False,10
466,ST467,Delhi,2025-10-15,Car,08:42,09:38,46.5,465.0,Cash,2025-10-15 08:42:00,2025-10-15 09:38:00,56.0,8,9,Wednesday,False,10
474,ST475,Delhi,2025-10-15,Car,11:36,13:07,83.6,836.0,Card,2025-10-15 11:36:00,2025-10-15 13:07:00,91.0,11,13,Wednesday,False,10
479,ST480,Delhi,2025-10-15,Car,15:49,18:24,29.7,297.0,Card,2025-10-15 15:49:00,2025-10-15 18:24:00,155.0,15,18,Wednesday,False,10
494,ST495,Delhi,2025-10-15,Bike,14:24,15:42,30.9,309.0,UPI,2025-10-15 14:24:00,2025-10-15 15:42:00,78.0,14,15,Wednesday,False,10
497,ST498,Delhi,2025-10-15,Truck,16:55,18:21,30.8,308.0,Cash,2025-10-15 16:55:00,2025-10-15 18:21:00,86.0,16,18,Wednesday,False,10

In [18]:
usage_df = usage_df[usage_df["City"] == "Delhi"].copy()

In [19]:
usage_df.info()
usage_df.reset_index(drop=True, inplace=True)

<class 'pandas.DataFrame'>
Index: 58 entries, 6 to 497
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Station_ID                58 non-null     str
 1   City                      58 non-null     str
 2   Date                      58 non-null     datetime64[us]
 3   Vehicle_Type              58 non-null     str
 4   Charging_Start_Time       58 non-null     str
 5   Charging_End_Time         58 non-null     str
 6   Energy_Consumed_kWh       58 non-null     float64
 7   Cost_INR                  58 non-null     float64
 8   Payment_Method            58 non-null     str
 9   Charging_Start            58 non-null     datetime64[us]
 10  Charging_End              58 non-null     datetime64[us]
 11  Session_Duration_Minutes  58 non-null     float64
 12  Start_Hour                58 non-null     int32
 13  End_Hour                  58 non-null     int32
 14  Day_of_Week               58 non-null     str
 15  Is_Weekend                58 non-null     bool
 16  Month                     58 non-null     int32
dtypes: bool(1), datetime64[us](3), float64(3), int32(3), str(7)
memory usage: 7.1 KB

In [20]:
usage_df["Vehicle_Type"].value_counts()

Vehicle_Type
Truck    16
Bike     16
Car      15
Bus      11
Name: count, dtype: int64

In [21]:
usage_df["supports_2W"] = (usage_df["Vehicle_Type"] == "Bike").astype(int)

usage_df["supports_3W"] = 0

usage_df["supports_4W"] = (
    usage_df["Vehicle_Type"].isin(["Car", "Bus", "Truck"])
).astype(int)